/*
 * This source file was generated by the Gradle 'init' task
 */
package hmmtest1;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@Getter
@Setter
public class App {

    public String getGreeting() {
        log.info("ça parle !!!");
        return "Hello World!";
    }

    public static void main(String[] args) {
        log.info(new App().getGreeting());
        // System.out.println(new App().getGreeting());
    }
}
