/*
 * This source file was generated by the Gradle 'init' task
 */
package com.r3edge.engine.examples.hmm;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {

    public String getGreeting() {
        // Comment inutile
        log.info("ça parle bien, très bien même !!!");
        return "Hello World!";
    }

    public static void main(String[] args) {
        // tout passe des logs
        log.info(new App().getGreeting());
    }
}
